InlandMarinaApp/Models/ErrorViewModel.cs
namespace InlandMarinaApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InlandMarinaApp/Components/UnleasedSlipsByDockViewComponent.cs
using MarinaData;
using Microsoft.AspNetCore.Mvc;
namespace MoviesMVC.Components
{
    public class UnleasedSlipsByDockViewComponent : ViewComponent
    {
        private InlandMarinaContext _context { get; set; }

        // constructor with parameter - context object injected into the controller
        public UnleasedSlipsByDockViewComponent(InlandMarinaContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id) //dock id
        {
            List<Slip> slips = null;
            if (id == 0) // code for all
            {
                slips = MarinaManager.GetUnleasedSlips(_context);
            }
            else
            {
                slips = MarinaManager.GetUnleasedSlipsByDock(_context, id); // filter accordingly
            }
            return View(slips); // the view for the view component is called Default.cshtml
        }
    }
}

InlandMarinaApp/Controllers/AccountController.cs
using MarinaData;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace RentalsMVC.Controllers
{
    public class AccountController : Controller
    {
        private InlandMarinaContext _context { get; set; }

        // context injected to the constructor
        public AccountController(InlandMarinaContext context)
        {
            _context = context;
        }
        // HttpGet method; default. It's IActionResult because it can be a redirect
        public IActionResult Login(string? returnUrl = "") // when user logs in, send them back to the page they requested from
        {
            if (returnUrl != "")
            {
                TempData["ReturnUrl"] = returnUrl;
            }
            return View();
        }

        // post method for login using async call to http context
        [HttpPost]
        public async Task<IActionResult> LoginAsync(Customer user) // user data from the login form
        {
            Customer usr = CustomerManager.Authenticate(_context, user.Username, user.Password);
            if (usr == null)
            {
                return View(); // stay on the login page
            }
            // authentication passed. ie. usr is not null

            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, usr.Username)
            };
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme); // could've just type "Cookies"
            ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            HttpContext.Session.SetInt32("CurrentCustomer", usr.ID!); 

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            if (String.IsNullOrEmpty(TempData["ReturnUrl"]?.ToString())) // no return url
            {
                return RedirectToAction("Index", "Home"); // home page
            }
            else
            {
                return Redirect(TempData["ReturnUrl"]!.ToString()!);
            }
        }

        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme); // "Cookies" .. but text is text. 
            HttpContext.Session.Remove("CurrentCustomer");
            return RedirectToAction("Index", "Home"); // home page
        }

        public IActionResult AccessDenied() // automatically picked up by MVC to a more friendly page when failed authorization attribute.
        {
            return View();
        }
    }
}

InlandMarinaApp/Controllers/HomeController.cs
using InlandMarinaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InlandMarinaApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("[action]")]
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InlandMarinaApp/Controllers/SlipsController.cs
using MarinaData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InlandMarinaApp.Controllers
{
    public class SlipsController : Controller
    {
        private InlandMarinaContext _context { get; set; }

        public SlipsController(InlandMarinaContext context)
        {
            _context = context;
        }

        // GET: SlipsController
        public ActionResult Index()
        {
            try
            {
                // prepare the docks list for the selected element (dropdown)
                List<Dock> docks = MarinaManager.GetDocks(_context);
                var list = new SelectList(docks, "ID", "Name").ToList(); // to add "All" option. otherwise we'd have SelectList
                list.Insert(0, new SelectListItem("All Docks", "0")); // 0 as the value for All.
                ViewBag.Docks = list; //define viewbag

                return View(); // no data passed to the view because this will call the view component to get the data (AJAX)
            } catch
            {
                TempData["Message"] = $"Something went wrong with populating Slips. Try again later.";
                TempData["IsError"] = "True";
                return RedirectToAction("Index", "Home");
            }
        }

        // method to be called from AJAX function
        public ActionResult GetUnleasedSlips(int id) // dock id
        {
            // invoke default view component
            return ViewComponent("UnleasedSlipsByDock", id);
        }


        [Authorize]
        public ActionResult Lease()
        {
            try
            {
                List<Slip> slips = MarinaManager.GetUnleasedSlips(_context);
                var list = new SelectList(slips, "ID", "ID");
                ViewBag.Slips = list;
                int? customerID = HttpContext.Session.GetInt32("CurrentCustomer")!;
                if (customerID != null)
                {
                    ViewBag.CustomerID = customerID;
                }
                else
                {
                    ViewBag.CustomerID = 0; // dummy
                }
                return View(new Lease());
            }
            catch
            {
                TempData["Message"] = $"Something went wrong with populating Lease page. Try later.";
                TempData["IsError"] = "True";
                return RedirectToAction("Index", "Home");
            }
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Lease(int id, Lease newLeaseData)
        {
                if (ModelState.IsValid) // check the validation attributes in the Lease class
                {
                        MarinaManager.AddLease(_context, newLeaseData);
                        TempData["Message"] = $"Successfully added Lease for Slip #{newLeaseData.SlipID}";
                    // no need to set up IsError
                    return RedirectToAction(nameof(MySlips));
                }
                else
                {
                    TempData["Message"] = $"Something went wrong with adding lease. Try later.";
                    TempData["IsError"] = "True";
                    return View("Lease", newLeaseData); // if errors, stay on the same page with content
                }   
        }
        [Authorize]
        public ActionResult MySlips()
        {
            // get the cookie from the logged in user. 
            int? customerId = HttpContext.Session.GetInt32("CurrentCustomer");
            // prepare the list of leases by customer id with the cookie
            List<Slip> slips = MarinaManager.GetLeasedSlipsByCustomerId(_context, customerId);

            return View(slips);
        }
    }
}

InlandMarinaApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

<div class="text-center">
    <h1 class="display-4">Contact</h1>
    
    <table class="table table-light">
        <tr>
            <td>Address</td>
            <td>Inland Lake Marina<br/> 
                Box 123<br/>
                Inland Lake, Arizona <br/>
                86038
            </td>
        </tr>
        <tr>
            <td>Office Phone</td>
            <td>928-555-2234</td>
        </tr>
        <tr>
            <td>Leasing Phone</td>
            <td>928-555-2235</td>
        </tr>
        <tr>
            <td>Fax</td>
            <td>928-555-2236</td>
        </tr>
        <tr>
            <td>Manager</td>
            <td>Glenn Cooke</td>
        </tr>
        <tr>
            <td>Slip Manager</td>
            <td>Kimberley Carson</td>
        </tr>
        <tr>
            <td>Contact E-mail</td>
            <td>info@inlandmarina.com</td>
        </tr>
    </table>
</div>
<a href="@Url.Action("Index", "Home")">Home Page</a>

InlandMarinaApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        Welcome to Inland Marina located on the south shore Inland Lake, just a small commute from major
        centers in the southwest.
    </p>
    <p>
        Inland Marina was established in the 1967 shortly after Inland Lake was created as a result of the
        Southwest dam. From its humble beginnings, it has grown to be the largest marina on Inland Lake. Due
        to the warm climate that extends year-round, Inland Lake has become a popular tourist destination in
        the southwest. Boat owners from California, Arizona, Nevada, and Utah are attracted to the area.
        Inland Marina has 90 slips ranging in size from 16 to 32 feet in length. Dock services include electrical
        and fresh water.
    </p>
</div>
<a href="@Url.Action("Contact", "Home")">Contact Page</a>

InlandMarinaApp/Views/Shared/Components/UnleasedSlipsByDock/Default.cshtml
@model IEnumerable<MarinaData.Slip>

@{
    Layout = null;
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dock.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
            </tr>
        }
    </tbody>
</table>

InlandMarinaApp/Views/Shared/_Layout.cshtml
@{
    string controller =
        ViewContext.RouteData.Values["controller"]?.ToString() ?? "";
    string action =
        ViewContext.RouteData.Values["action"]?.ToString() ?? "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inland Marina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InlandMarinaApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="text-center">
            <img src="~/images/inlandbanner_v3_800x100.jpg" class="rounded img-responsive" alt="corporate banner" />
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inland Marina</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller == "Home" && action == "Index" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller == "Slips" && action == "Index" ? "active" : "")" asp-area="" asp-controller="Slips" asp-action="Index">Slips</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark @(controller == "Slips" && action == "Lease" ? "active" : "")" asp-area="" asp-controller="Slips" asp-action="Lease">Lease</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark @(controller == "Slips" && action == "MySlips" ? "active" : "")" asp-area="" asp-controller="Slips" asp-action="MySlips">My Slips</a>
                            </li>
                        }
                    </ul>
                    <ul>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData["Message"] != null)
        {
            <h4 class="@(TempData["isError"] != null ? "border-danger" : "border-success") border">
                @TempData["Message"]
            </h4>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Inland Marina
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InlandMarinaApp/Views/Slips/Index.cshtml
@{
    ViewData["Title"] = "Slips";
}

<h1>Available Slips</h1>
<div>
    <select id="uxDocks" asp-items="@ViewBag.Docks" class="form-select"></select>
</div>

<div id="uxDisplay">
    @await Component.InvokeAsync("UnleasedSlipsByDock", "0")
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#uxDocks").change(function () {
                var dockID = $("#uxDocks").val();
                $.ajax({
                    method: 'GET',
                    url: '/Slips/GetUnleasedSlips',
                    data: { id: dockID }
                }).done(function (result, statusText, xhdr) {
                    $("#uxDisplay").html(result);
                }); @* closes done *@
                    }); @* closes change *@
                }); @* closes ready *@
    </script>
}

InlandMarinaApp/Views/Slips/Lease.cshtml
@model MarinaData.Lease

@{
    Model.CustomerID = ViewBag.CustomerID;
}

<h1>Lease</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Lease" method="post">
            <p>
                <label asp-for="SlipID" class="control-label"></label>
                <select name="SlipID" asp-items="@ViewBag.Slips" asp-for="SlipID" class="form-select"></select>
            </p>
            <div class="form-group">
                <input asp-for="CustomerID" class="form-control" hidden readonly />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

InlandMarinaApp/Views/Slips/MySlips.cshtml
@model IEnumerable<MarinaData.Slip>

@{
    ViewData["Title"] = "Slips";
}

<h1>My Slips</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dock.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
            </tr>
        }
    </tbody>
</table>